# num=int(input("enter the number"))
# if (num<10):
#     print("less than 10")
# elif(num<20):
#     print("less than 20")
# else:
#     print("greater than 20")


# x=int(input("enter no:"))
# y=int(input("enter no:"))
# if x>y==0:
#     print(x)
# else:
#     print(y)

# num=int(input("enter no:"))
# x=input("enter operator:")
# num1=int(input("enter no:"))
# if x=="+":
#     print(num+num1)
# elif x=="-":
#     print(num-num1)
# elif x=="%":
#     print(num%num1)
# elif x=="/":
#     print(num/num1)
# elif x=="//":
#     print(num//num1)
# elif x=="*":
#     print(num*num1)
# elif x=="**":
#     print(num**num1)

# x=int(input("enter no:"))
# y=int(input("enter no:"))
# z=int(input("enter no:"))
# if x>y and x>z:
#     print(x)
# elif y>x and y>z:
#     print(y)
# elif z>x and z>y:
#     print(z)
# else:
#     print("nothing")


# x=input("enter alphabet:")
# if x>="a" and x<="z"or x>"A" and x<"Z":
#     print("it is alphabet")
# else:
#     print("not alphabet")



# x=input("enter vowel:")
# if x=="a" or x=="e" or x=="i" or x=="o" or x=="u":
#     print("vowels")
# else:
#     print("not ")


# x=int(input("enter current year:"))
# y=int(input("enter birth year:"))
# if "x-y":
#     print(x-y)


# x=int(input("enter year:"))
# if x%4==0 and x%100!=0 or  x%400==0:
#     print(x,"leap year")
# else:
#     print("not")



# x=int(input("enter days in month:"))
# if x==31:
#     print("january,march,may,july,august,october,december")
# elif x==30:
#     print("april,may,june,september,november")
# elif x==28 or x==29:
#     print("februaruy")
# else:
#     print("not")


# x=int(input("enter day no:"))
# if x==1:
#     print("monday")
# elif x==2:
#     print("tuesday")
# elif x==3:
#     print("wednesday")
# elif x==4:
#     print("thursday")
# elif x==5:
#     print("fridauy")
# elif x==6:
#     print("saturday")
# elif x==7:
#     print("sunday")
# else:
    # print("nothjing")



# x=(input("enter alphabet:"))
# if x>="a" and x<="z":
#     print(x,"lower")
# elif x>="A" and x<="Z":
#     print(x,"upper")
# else:
#     print("nothing")



# x=int(input("enter no:"))
# y=int(input("enter no:"))
# z=int(input("enter no:"))
# if x==y==z:
#     print("equilateral")
# elif x==y or y==z or x==z:
#     print("isceles")
# else:
#     print("scalene")



# x=int(input("enter costprice:"))
# y=int(input("enter sellingprice:"))
# if x>y:
#     print(x-y,"loss")
# elif y>x:
#     print(y-x,"profit")
# elif x==y:
#     print(x==y,"no profit no loss")
# else:
#     print("not")


# x=int(input("enter number:"))
# if x>0:
#     print(x,"greater")
# elif x<0:
#     print(x,"less")
# else:
#     print("zero")


# x=int(input("enter no:"))
# if x<1:
#     print("fill more")
# elif x<=10:
#     print("no need")
# else:
#     print("overflow")

# var=int(input("enter no:"))
# vari=int(input("enter no:"))
# if var%vari==0:
#     print("divisible")
# else:
#     print("not divisible")


# num=int(input("enter number:"))
# if num%2==0:
#     print("even")
# else:
#     print("odd")
# if num%2!=0:
#     print("prime ")
# elif num==2:
#     print(" yes prime")
# else:
#     print("not prime")


# var=int(input("enter no:"))
# vari=int(input("enter no:"))
# if var>vari:
#     print(var)
# else:
#     print(vari)


