varx=int(input("enter the number"))
vary=int(input("enter the number"))
varz=input("enter the operator")
if (varz=="%"):
     print(varx%vary)
elif(varz=="*"):
    print(varx*vary)
elif(varz=="-"):                                                                                                               
    print(varx-vary)
elif(varz=="+"):
    print(varx+vary)
elif(varz=="/"):
    print(varx/vary)
elif(varz=="//"):
    print(varx//vary)
elif(varz=="**"):
    print(varx**vary)